import requests
import json

# Función para obtener transacciones
def get_transactions():
    url = "https://api.nequi.com/transactions"
    headers = {"Authorization": "Bearer eyJraWQiOiJuZVhiaFBIVkREV3IxXC9sZTl2YVdVQ0laNHlrSHZsUkF0bjFGajBRSVU3WT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1ZWdhNW5pYWY3NzFkZmVqZ2NiZzQycmY2NCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXBpXC90aGlyZHBhcnR5YXBwcyBhcGlcL2FnZW50cyBhcGlcL25vdGlmaWNhdGlvbnMgYXBpXC9wYXJ0bmVycyBhcGlcL21vbmV5bWFuYWdlbWVudCBhcGlcL3BheW1lbnRzIGFwaVwvc3Vic2NyaXB0aW9ucyBhcGlcL3JlcG9ydHMgYXBpXC9kaXNwZXJzaW9ucyBhcGlcL2V4dGVybmFscGF5bWVudHMgYXBpXC90cmFuc3BvcnQgYXBpXC9naWZ0Y29kZXMiLCJhdXRoX3RpbWUiOjE3MTkzMzM1MjgsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX202b21PQnFDWSIsImV4cCI6MTcxOTMzNzEyOCwiaWF0IjoxNzE5MzMzNTI4LCJ2ZXJzaW9uIjoyLCJqdGkiOiIyZTYxNmJjNC1hZTc1LTRkN2ItOTAyMC02M2QyYmNjZjlhNjQiLCJjbGllbnRfaWQiOiI1ZWdhNW5pYWY3NzFkZmVqZ2NiZzQycmY2NCJ9.pkpVPGsmvhsb9DKKHxbH1IbP5PNngvkm6R823iTBw_bMOIBhYW39Xj8ZH8KxqHmBUEUIFY34ULKs8Wdfg3AbCIw8ljIrj8NW03ea67c6DJyxJGC_hhjKxRMrSpXNWxExOfkT-z06Sd3mRw48UrHUVLAA31H2zjqDia2NQ0PVa_44sX-7yIGySsL7k0cwo8f6mhF65H4YRw421zz6lnvTdh6VwLfTSQoGHYgUvlxanmXCmbpsNNS7tSIptInV97RiHXo7pHEu5VSo4XZUJe4uPK7u_6fVEQzhTDnOMkGN2jLZ6_ifHPWb9Isz5HfEWWgFtpZzfYUd20b1PyQz0nG1Aw"}  # Reemplaza con tu token de acceso
    response = requests.get(url, headers=headers)
    return response.json()

# Obtener y mostrar transacciones
transactions = get_transactions()
print(json.dumps(transactions, indent=4))  # Imprime las transacciones en formato JSON con indentación
