import requests

API_URL = "https://api.example.com/kwPodOPY1O2DFRtBSfU6u91DBORteGnrS9S1Gjud"
access_token = "eyJraWQiOiJuZVhiaFBIVkREV3IxXC9sZTl2YVdVQ0laNHlrSHZsUkF0bjFGajBRSVU3WT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1ZWdhNW5pYWY3NzFkZmVqZ2NiZzQycmY2NCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXBpXC90aGlyZHBhcnR5YXBwcyBhcGlcL2FnZW50cyBhcGlcL25vdGlmaWNhdGlvbnMgYXBpXC9wYXJ0bmVycyBhcGlcL21vbmV5bWFuYWdlbWVudCBhcGlcL3BheW1lbnRzIGFwaVwvc3Vic2NyaXB0aW9ucyBhcGlcL3JlcG9ydHMgYXBpXC9kaXNwZXJzaW9ucyBhcGlcL2V4dGVybmFscGF5bWVudHMgYXBpXC90cmFuc3BvcnQgYXBpXC9naWZ0Y29kZXMiLCJhdXRoX3RpbWUiOjE3MTg5Nzk2MDEsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX202b21PQnFDWSIsImV4cCI6MTcxODk4MzIwMSwiaWF0IjoxNzE4OTc5NjAxLCJ2ZXJzaW9uIjoyLCJqdGkiOiJlMWQwNDMyNS0yMDk2LTQ4MjktYmJkMi1hYTAzZTFmNTk1NjMiLCJjbGllbnRfaWQiOiI1ZWdhNW5pYWY3NzFkZmVqZ2NiZzQycmY2NCJ9.iKvZFS3dEbgZ3n_OLFfXTmthADrOvZRP5Jy__3bx5L7RoZ3Tlx6bUqdCas4fN8bdYFyjz7zAWB8vRuaxP4d8Ug5HLtwLGTroSE_8x4ItM6-lVeH61gtIxEdewsXdNLNZRY-f_A0ho9YouWKRc7-pUOEisi1vRv8AeDvCUo-tr-VOsI5iT_ZhnzcxkLtK2UkWdaKwZTnlU7U4Tet-rdXLQXT8fU-XtUtZ4911KBneFAvYSzYsQSBbcjVtsXWbnvaIkaE7-uNLgqFCjDYSuRmXv_EML4J2WRPHhFs89oPbLobDFHbMgsUlNlTroTYvxN07BcvYuyMWnL8KH9EjrYJCMw",


headers = {
    "Authorization": f"Bearer {access_token}",
    "Content-Type": "application/json"
}

response = requests.get(API_URL, headers=headers)

if response.status_code == 200:
    print("Request successful:", response.json())
else:
    print("Request failed:", response.status_code, response.text)
